configs:
  - classificator: sklearn.linear_model.LogisticRegression
    params:
      penalty: l2
      dual: false
      tol: 0.0001
      C: 1.0
      fit_intercept: true
      intercept_scaling: 1
      random_state: null
      solver: lbfgs
      max_iter: 100
      multi_class: auto
      verbose: 0
      warm_start: false
      n_jobs: null
      l1_ratio: null
  - classificator: sklearn.neighbors.KNeighborsClassifier
    params:
      n_neighbors: 5
      weights: uniform
      algorithm: auto
      leaf_size: 30
      p: 2
      metric: minkowski
      metric_params: null
      n_jobs: 1
  - classificator: sklearn.svm.SVC
    params:
      C: 1.0
      kernel: rbf
      degree: 3
      gamma: scale
      coef0: 0.0
      shrinking: true
      probability: false
      tol: 0.001
      cache_size: 200
      verbose: false
      max_iter: -1
      decision_function_shape: ovr
      break_ties: false
      random_state: null
  - classificator: sklearn.naive_bayes.GaussianNB
    params:
      priors: null
      var_smoothing: 0.000000001
  - classificator: sklearn.tree.DecisionTreeClassifier
    params:
      criterion: gini
      splitter: best
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0.0
      max_features: null
      random_state: null
      max_leaf_nodes: null
      min_impurity_decrease: 0.0
      ccp_alpha: 0.0
